### ISSUE TITLE
Logo customization

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#124]
Offer customer to have their Logo on the first WebApp page 'Enable skip the password'.

Customer to provide URL to get the Logo.

**Comment by mike-cast** [comment]
Design: https://www.figma.com/file/wO3RNuKF3NEmTZcPXUNtrO/Demos?node-id=330%3A112

Screens
![Screen Shot 2021-03-08 at 11.41.12 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/c83b9b73-b63f-4fb9-99f5-5cf5c65abbba)
