### ISSUE TITLE
Checkmark in the last page to be replaced with OwnID Logo

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#126]
Mike to consider animation of the Logo.

**Comment by mike-cast** [comment]
Design: https://www.figma.com/file/wO3RNuKF3NEmTZcPXUNtrO/Demos?node-id=330%3A574

Screen
![Screen Shot 2021-03-08 at 11.42.38 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/2feb05e3-293a-4cd2-88fd-18f6c0d11b88)
