### ISSUE TITLE
Link account - design enhancements

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-web-ui-sdk#19]

**Comment by giladvidal** [comment]
From Mike:
Desktop Design
https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1552%3A77

Mobile Design
https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=37%3A258

Prototype
https://www.figma.com/proto/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1552%3A77&viewport=1802%2C-1564%2C0.1415356695652008&scaling=min-zoom
