### ISSUE TITLE
Magic link UI 

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-web-ui-sdk#20]
SoW:

- Web-ui-sdk changes

**Comment by giladvidal** [comment]
From Mike:
Designs
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1187%3A2

Prototype
https://www.figma.com/proto/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=1187%3A2&viewport=1015%2C566%2C0.15007957816123962&scaling=min-zoom
