### ISSUE TITLE
When get account not found message change 'Skip the password' to disabled

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-web-ui-sdk#25]
When a user try to login but does not have an account, they get an error in the login page (unless provided email and then being asked to enter password for the last time). In addition the 'Skip the password' is checked with green. 

The task is to remove the green checkmark and set 'Skip the password' to disabled.

https://www.figma.com/file/10OJucsIapGTtPZtVefiTS/?node-id=0%3A1

**Comment by giladvidal** [comment]
From Mike:
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/FIDO2-Inline-skip-the-password?node-id=775%3A220

**Comment by bdonchenko** [comment]
@craimundo77 @giladvidal please discuss requirements and reflect it in designs.

**Comment by mike-cast** [comment]
Updated designs: https://www.figma.com/file/10OJucsIapGTtPZtVefiTS/?node-id=0%3A1
