### ISSUE TITLE
Link account message during processing

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-web-ui-sdk#26]
Instead of 'Linking your account' set something more generic like 'Loading'.

**Comment by giladvidal** [comment]
From Mike:
https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1220%3A338

**Comment by akayomov** [comment]
Not clear description. I can't find any link screens in figma page. i don't understand where message should be changed. Is it widget or web app? which flow? link-on-login? link-in-app?

**Comment by akayomov** [comment]
closing without testing.
ticket is over covered in #19
