### ISSUE TITLE
Widget is stuck if onRecover handler is not provided

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-web-ui-sdk#28]
## Steps to reproduce
1. add ownid widget with type `recover`
1. do not set `onRecover` call back
1. try to recover user

#### Excepted results
after a successful recovery, popup disappear 

#### Actual result
popup indicates that loading is not completed

![Password_Reset___DAIMANI.png](https://zenhub.wdf.sap.corp/images/5ed662f61762c656b93b7c51/ed32cbb3-ca32-4dac-b95c-134c471c3b62)

**Comment by vitalii-marynkevych** [comment]
@akayomov please also test in IE11
