### ISSUE TITLE
In-app widget has not translated string "You have instant login enabled"

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-web-ui-sdk#34]
![image.png](https://zenhub.wdf.sap.corp/images/5efcbcbd9b884c0fa934d045/a1ec8605-64c7-4c71-815f-09dd72b03f50)

**Comment by giladvidal** [comment]
From Alex:
![image.png](https://images.zenhubusercontent.com/5fd2339be5d8bc1d8b14aa91/bdb956d0-92f8-4a0e-80cd-b5708b0becaa)

**Comment by giladvidal** [comment]
![image.png](https://images.zenhubusercontent.com/5fd2339be5d8bc1d8b14aa91/16998acd-f1d8-4b74-bfe2-01331c626621)

**Comment by akayomov** [comment]
Still no translations for theese parts:
![image.png](https://images.zenhubusercontent.com/5fd6737046b97edfd6d4a506/a07f62cc-6d0c-46df-85c3-edbb03670a7b)
![image.png](https://images.zenhubusercontent.com/5fd6737046b97edfd6d4a506/c47e16cb-916f-40f9-929f-a315a469e145)

**Comment by Tony-Pa** [comment]
for now, we have only English translations, other locales will provide translation team
