### ISSUE TITLE
Customer - ask to confirm password in login 3 times

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#44]
When entering a password in the login to link the account, they say:
-	Next time I wanted to log in, it asked me again for the password to confirm 
-	At the third attempt, I was able to complete it

Using Walldorf VPN:
https://accstorefront.cv4c9dq9b-daimaniag1-s1-public.model-t.cc.commerce.ondemand.com/global/en

**Comment by akayomov** [comment]
![image.png](https://images.zenhubusercontent.com/5fd6737046b97edfd6d4a506/f2fd7977-a779-4285-8d19-ce680bb743fd)

I was not able to register with skip the password. Is that the defect they were reporting about? @giladvidal

**Comment by giladvidal** [comment]
@akayomov - yes. is that fixed already?

**Comment by akayomov** [comment]
no. i just reproduced it. Tested in iPhone with FIDO2 enabled. issue still exists

**Comment by akayomov** [comment]
*Steps to reproduce:*
1. Click "Register" button at black footer (bottom of the page)
2. In appeared popup fill correct email twice
3. Click "Skip the password" button
4. Scan QR code
5. Proceed register flow successfully in webapp
6. Click "GO" button on popup
**Actual Result:** Registration not happening (screenshot is above)
**Expected:** System should register user succesfully

**Comment by giladvidal** [comment]
@akayomov - actually you refer to ticket 41 that Anton said is fixed.
which environment you checked?

**Comment by akayomov** [comment]
@giladvidal I used a link from description

**Comment by giladvidal** [comment]
@akayomov - dev is ok?

**Comment by akayomov** [comment]
@giladvidal - yes. but it's different configuration i believe
