### ISSUE TITLE
UI SDK improvements for easy integration

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#55]
When integrating to a website, probably there will be a problem with the password as it will be missing when using OwnID 'skip the password'. For that maybe better to include in OwnID widget an API to generate a random password (to make it easier for the developer to set a password).

SoW:

Update documentation with an example for the developer of how to generate random password. The idea: to simplify developer's life :)

**Comment by bdonchenko** [comment]
1. There can be different requirements for a password on different websites. So only website devs know it.
1. DOM manipulation with input won't work in frameworks like Angular, Vue, React etc....

This ticket should not be done.

**Comment by giladvidal** [comment]
Right. 
So at least let's have a comment on that in the docs so a developer will know it should be handled.
