### ISSUE TITLE
magic link - expose error message

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#65]
When the user open the link from a different browser, they get the login page and don't understand why they were not logged-in.

Mike - create a sentence to explain the problem to the user

Developer -
- have the message available for the application to display to the user
- also in case other problem pass Gigya error

**Comment by mike-cast** [comment]
Text
Magic link login failed. Make sure you’re using the same browser that initiated the magic link request.

Design
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1949%3A13807

Screen
![Screen Shot 2021-01-28 at 3.49.24 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/45396c15-da4c-4122-9b32-36156692315c)
