### ISSUE TITLE
magic link - link color

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#66]
This is regarding the 'don't have your phone' message:
- when hover, make blue
- underline the existing gray text

**Comment by mike-cast** [comment]
Prototype
https://www.figma.com/proto/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1187%3A2&viewport=1405%2C870%2C0.24060608446598053&scaling=min-zoom

Designs
https://www.figma.com/file/dlZX0QHeDNFD1PQQNWmqNA/Skip-the-password?node-id=1187%3A26

Screens
![Screen Shot 2021-01-27 at 9.27.21 AM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/ada5a9f1-853c-44cf-b027-7ff20aca042c)
