### ISSUE TITLE
Console - update Admin flow

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#86]
After login, the admin can access his profile to update first name/last name/company/email. This will trigger Rest call to the server.

In the design, it is under Manager in the first row.

Use Gigya screen-sets

Email is read-only if it's not supported by Screen-sets
Delete account is out of scope if it's not supported by Screen-sets

UPD: agreed with Carlos that it will be easier to implement this form without Gigya screen sets

**Comment by bdonchenko** [comment]
does Gigya support email update?
