### ISSUE TITLE
magic link - create back button

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-web-ui-sdk#94]
back button where user is being asked for their email.

**Comment by mike-cast** [comment]
Designs:
https://www.figma.com/file/HMLGebZRMAeaGp62lK2zRs/Login?node-id=10%3A187

Prototype of dialog box only:
https://www.figma.com/proto/HMLGebZRMAeaGp62lK2zRs/Login?node-id=28%3A81&viewport=2810%2C781%2C0.9706047177314758&scaling=min-zoom
